(defun normalize ()
  (interactive)
  (let ((start (point)))
    (while (not (and (bolp)(eolp)))
      (while (search-forward " " (line-end-position) t)
	(delete-char -1)
	(insert "\n"))
      (forward-line 1)
      )
    (sort-lines nil start (point))
    (forward-line 1)
    ))
